### PR TITLE
Block 1 Option

### PR DESCRIPTION
**Pull request by ea2973929**
Also refactored so that options-code is now in a separate file. I think as this grows having everything in packet.rs would be cumbersome. Hope you like it.

### CODE REVIEW

**Comment by Covertness** [comment]
I think the package version need to upgrade because of some API changed.

**Comment by ea2973929** [comment]
Right, not sure how you want to handle this.

I was thinking something like not updating release version until all
functionality is there that we want, whatever that means.

I try to make a pull request as soon as I have something ready that works
reasonably well, but I still predict there will be more of them for the
Block1 transfer.

Maybe I should make pull requests to some feature branch instead of master
for a while? I do like to be able to break it up in small pieces in case
you don't like the direction I'm taking, I'll know about it early.

I guess the remaining Block1-transfer work that I predict is:

* A new BlockTransfer struct and API for performing a Block1 PUT or POST.
It will be a separate file 'block_transfer.rs' (analog to observer.rs) and
will have an API in client.rs I think.
* An implementation in server.rs that can receive all the blocks and put
them together on the server side. (Note that I personally don't need this,
as the receiving end is not a coap-rs server, but I think it would be
strange to omit it and still say that coap-rs supports Block1-transfers)

Then later on (maybe in the same release, but could also be at a later
stage)
* Client support for retrieving GET responses with Block2 options
* Server support for sending GET responses with Block2 options

I think it would be nice to have both in the same release, esp. since there
will be API-changes for all of them.

What do you think?

**Comment by Covertness** [comment]
Yeah. It makes sense. I add you as a collaborator. https://github.com/Covertness/coap-rs/invitations

**Comment by Covertness** [comment]
Block1/2 is supported in this repo.

**Pull request closed without merging**
