### PR TITLE
Respond from the CoAP port to support Copper

### PR DESCRIPTION
**Pull request by jamesmunns**
The Mozilla Copper plugin only recognizes messages that return from the CoAP port. Previously, responses were returned from a random UDP socket.

I have added a "CoAPResponse" class which is based on the CoAPClient class. This allows for responses from the server to be on the same port that requests were sent to.

### CODE REVIEW

**Comment by jamesmunns** [comment]
Sorry for the failing tests. Still learning how to develop rust, including how to run tests locally. I think I have it all fixed now.

**Comment by jamesmunns** [comment]
@Covertness, not sure what is wrong with the appveyor test. Travis tests pass, and this test passes locally for me. Perhaps this is a networking issue?

**Comment by Covertness** [comment]
Can you add another `new ` method to meet your need ? The `CoAPResponse` class has some duplicate code.

**Comment by jamesmunns** [comment]
I did check this, however `mio::udp::UdpSocket` is used in one file, and `std::net::UdpSocket` is used in the other. I was not able to merge them together perfectly, however I will take another look.

**Comment by Covertness** [comment]
Thank you. I think you can replace `std::net::UdpSocket` with `mio::udp::UdpSocket` for the client.

**Comment by jamesmunns** [comment]
@Covertness I don't think it is necessary for the client to have a "reply" functionality. CoAP is REST-style, so generally the client would just make another request, as opposed to a reply.

Please let me know if this is acceptable for you.

**Comment by jamesmunns** [comment]
@Covertness rebased and squashed commits

**Comment by Covertness** [comment]
@jamesmunns I read your commit and found [the socket is used in the thread pool](https://github.com/jamesmunns/coap-rs/blob/copper-support/src/server.rs#L58). Writing the same socket concurrently can cause some problems. I think it also make [the Windows test failed](https://ci.appveyor.com/project/Covertness/coap-rs/build/1.0.32#L164).

**Comment by jamesmunns** [comment]
@Covertness thanks for pointing this out. I will look into adding a mutex to make this safe

**Comment by Covertness** [comment]
@jamesmunns `mutex` is ineffective and maybe make the program deadlock. I think [the Channel](http://rustbyexample.com/std_misc/channels.html) is more fit with this situation.

**Comment by jamesmunns** [comment]
I have a first, very ugly version using channels on this branch: https://github.com/jamesmunns/coap-rs/tree/port-share-chan, I will work on cleaning it up, and making it more usable.

I won't be committing to this pull request until I have my changes cleaned up.

**Comment by Covertness** [comment]
@jamesmunns Thanks. I think [the loop](https://github.com/jamesmunns/coap-rs/blob/port-share-chan/src/server.rs#L134) should be exited when stop the server.

**Comment by jamesmunns** [comment]
@Covertness Yup, I agree with you. I didn't get to that last night. I will figure out a good way to do that before I update this pull request. There is still a lot to clean up and make more usable

**Comment by jamesmunns** [comment]
Okay, fairly large change now, but I feel that the interface is now pretty usable. The user handler now has the signature:

```
fn handle(request: Packet) -> Option<Packet> { ... }
```

If the server would like to respond, they return a `Some<Packet>` type. If they have no response (or there is an error), they may respond with `None`.

I have also removed `reply()` from the client (it has no purpose now), and added a similar function in `Packet`'s `impl` called `auto_respond()`, which can be used similarly to the way `reply` was used before.

Please let me know what you think.

**Comment by Covertness** [comment]
I think `auto_respond()` can be removed. The response generated in `auto_respond()` should be initialized before the interface `handle`. Then the user handler would be:
```rust
fn handle(request: Packet, response: Packet) -> Option<Packet> { ... }
```

And why [this panic](https://github.com/jamesmunns/coap-rs/blob/copper-support/src/server.rs#L86) was commented ?

**Comment by jamesmunns** [comment]
@Covertness in my mind, not all handlers would generate a response, so creation of the response automatically would be unnecessary, however this may have been premature optimization. I will likely keep the function, but perform it automatically an internally (so the user's handler is not required to use it.

The removed panic was probably a mistake. I will restore it. I will also be introducing logging from the `log` crate in my next commit, if that is okay with you (if the user of this crate does not implement a logging handler, it is very little overhead, and makes debugging easier).

Also, do you have a Windows environment you can test this on? I don't know why the Appveyor tests continue to fail, and I do not have a Windows machine (or VM) handy that I can use to debug further. I would appreciate the help if you can provide it.

**Comment by jamesmunns** [comment]
@Covertness I just remembered about non-confirmable messages. Which of these would you prefer?

* Handlers must call `auto_respond()` and receive an `Option<Packet>` if it is a respondable message
* The signature of handle is: `fn handle(request: Packet, response: Option<Packet>) -> Option<Packet> {}`

**Comment by Covertness** [comment]
@jamesmunns I prefer to give the response by the `handle`. It make the interface easier to use.

I will look into the Windows build. I think the error maybe caused by the `mio`. Because the asynchronous I/O is provided by `IOCP` on the Windows. But on the Linux it is provided by `epoll`.

**Comment by jamesmunns** [comment]
@Covertness I think I have addressed all of your comments. Let me know if I can help troubleshoot the Windows issue. I did increment the version from `0.3.1` to `0.4.0` because there was a breaking interface change.

**Comment by Covertness** [comment]
@jamesmunns Thanks. I will try to remove `mio` for fixing the Windows issue. After the issue is fixed, I will merge this request.

**Comment by Covertness** [comment]
@jamesmunns I found `send_to` didn't work on the Windows. I open [an issue](https://github.com/carllerche/mio/issues/411) in the `mio` project. The Windows users are very few. I will merge this pull request at first.

**Pull request merged**
