### PR TITLE
Block transfer

### PR DESCRIPTION
**Pull request by ea2973929**
Works.

Some things left to be done:
* MessageID for all messages are 0 -> Suggestions on how to best fix this are welcome. I made a proposal a while back

* Should parse and respect Block1 block size suggestions in the response from the server: According to Section 2.3 in https://datatracker.ietf.org/doc/rfc7959/

* The current implementation is just one function: block_transfer::send(). It could be a member function of the CoAPClient, should it?

### CODE REVIEW

**Comment by Covertness** [comment]
Awesome!
Yeah. Please add a member function of the CoAPClient. So that others can use this feature easily.

**Comment by Covertness** [comment]
Any update about this pr? @ea2973929

**Comment by ea2973929** [comment]
It's mostly done, I didn't like that the test coverage dropped though so I'm restructuring a bit to be able to unit test at least some parts of the implementation. I'll see if I can find some time to finish it this weekend or so.

**Comment by jasta** [comment]
I've been trying to make this work as well and ended up going a very different direction with https://github.com/jasta/coap-server-rs, hopefully that might be useful for other folks so linking it here.

**Pull request closed without merging**
