### PR TITLE
Packet refactor

### PR DESCRIPTION
**Pull request by jamesmunns**
Still planning to add some tests, but please feel free to review. I can also squash the commits once we are ready (I included them in case you wanted to see the steps).

### CODE REVIEW

**Comment by jamesmunns** [comment]
@Covertness ready to merge.

**Comment by ptxmac** [comment]
You accidentally removed `use coap::{CoAPServer, CoAPClient};` from the README

**Comment by jamesmunns** [comment]
Thanks for the catch. Is there any way to get `cargo test` to run the README.md examples so I can catch this in the future?

**Comment by ptxmac** [comment]
A quick google search shows that the idea have been raised, but not closed: https://github.com/rust-lang/cargo/issues/383 
A possibility would be to try and add something like `rustdoc --test README.md` to the travis script

**Comment by Covertness** [comment]
The README example has another problem:
```
fn request_handler(req: CoAPRequest) -> Option<CoAPResponse> {
    println!("Receive request: {:?}", req);
    response
}
```
`response` should be `request.response` or `None `?

**Comment by jamesmunns** [comment]
Made changes, the suggested rustdoc command didn't seem to work for me. I will look into this before adding it to the travis script. See below. Thanks again for the spot.

```
MacBook-Pro-2:coap-rs james$ rustdoc --test coap-rs/README.md 
error reading `coap-rs/README.md`: No such file or directory (os error 2)
MacBook-Pro-2:coap-rs james$ rustdoc --test README.md 

running 3 tests
test coap_rs_0 ... FAILED
test coap_rs_2 ... FAILED
test coap_rs_1 ... FAILED

failures:

---- coap_rs_0 stdout ----
	<anon>:2:5: 2:23 error: can't find crate for `coap` [E0463]
<anon>:2     extern crate coap;
             ^~~~~~~~~~~~~~~~~~
error: aborting due to previous error
thread 'coap_rs_0' panicked at 'Box<Any>', ../src/libsyntax/errors/mod.rs:613
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'coap_rs_0' panicked at 'couldn't compile the test', ../src/librustdoc/test.rs:275

---- coap_rs_2 stdout ----
	<anon>:1:1: 1:19 error: can't find crate for `coap` [E0463]
<anon>:1 extern crate coap;
         ^~~~~~~~~~~~~~~~~~
error: aborting due to previous error
thread 'coap_rs_2' panicked at 'Box<Any>', ../src/libsyntax/errors/mod.rs:613
thread 'coap_rs_2' panicked at 'couldn't compile the test', ../src/librustdoc/test.rs:275

---- coap_rs_1 stdout ----
	<anon>:1:1: 1:19 error: can't find crate for `coap` [E0463]
<anon>:1 extern crate coap;
         ^~~~~~~~~~~~~~~~~~
error: aborting due to previous error
thread 'coap_rs_1' panicked at 'Box<Any>', ../src/libsyntax/errors/mod.rs:613
thread 'coap_rs_1' panicked at 'couldn't compile the test', ../src/librustdoc/test.rs:275


failures:
    coap_rs_0
    coap_rs_1
    coap_rs_2

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured
```

**Pull request merged**
